[build]
  publish = "docs"
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "bluetooth=(self)"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
